/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as BookHotelCodeRouteImport } from './routes/book.$hotelCode'
import { Route as ConfirmedTokenRouteImport } from './routes/confirmed.$token'
import { Route as OpsIndexRouteImport } from './routes/ops.index'
import { Route as OpsDriversRouteImport } from './routes/ops.drivers'
import { Route as OpsHotelsRouteImport } from './routes/ops.hotels'
import { Route as OpsLoginRouteImport } from './routes/ops.login'
import { Route as OpsVehiclesRouteImport } from './routes/ops.vehicles'
import { Route as OpsBookingsIndexRouteImport } from './routes/ops.bookings.index'
import { Route as OpsBookingsBookingIdRouteImport } from './routes/ops.bookings.$bookingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const BookHotelCodeRoute = BookHotelCodeRouteImport.update({
  id: '/book/$hotelCode',
  path: '/book/$hotelCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmedTokenRoute = ConfirmedTokenRouteImport.update({
  id: '/confirmed/$token',
  path: '/confirmed/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsDriversRoute = OpsDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => OpsRoute,
} as any)
const OpsHotelsRoute = OpsHotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => OpsRoute,
} as any)
const OpsLoginRoute = OpsLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => OpsRoute,
} as any)
const OpsVehiclesRoute = OpsVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => OpsRoute,
} as any)
const OpsBookingsIndexRoute = OpsBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsBookingsBookingIdRoute = OpsBookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => OpsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ops': typeof OpsRouteWithChildren
  '/book/$hotelCode': typeof BookHotelCodeRoute
  '/confirmed/$token': typeof ConfirmedTokenRoute
  '/ops/drivers': typeof OpsDriversRoute
  '/ops/hotels': typeof OpsHotelsRoute
  '/ops/login': typeof OpsLoginRoute
  '/ops/vehicles': typeof OpsVehiclesRoute
  '/ops/': typeof OpsIndexRoute
  '/ops/bookings/$bookingId': typeof OpsBookingsBookingIdRoute
  '/ops/bookings/': typeof OpsBookingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book/$hotelCode': typeof BookHotelCodeRoute
  '/confirmed/$token': typeof ConfirmedTokenRoute
  '/ops/drivers': typeof OpsDriversRoute
  '/ops/hotels': typeof OpsHotelsRoute
  '/ops/login': typeof OpsLoginRoute
  '/ops/vehicles': typeof OpsVehiclesRoute
  '/ops': typeof OpsIndexRoute
  '/ops/bookings/$bookingId': typeof OpsBookingsBookingIdRoute
  '/ops/bookings': typeof OpsBookingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ops': typeof OpsRouteWithChildren
  '/book/$hotelCode': typeof BookHotelCodeRoute
  '/confirmed/$token': typeof ConfirmedTokenRoute
  '/ops/drivers': typeof OpsDriversRoute
  '/ops/hotels': typeof OpsHotelsRoute
  '/ops/login': typeof OpsLoginRoute
  '/ops/vehicles': typeof OpsVehiclesRoute
  '/ops/': typeof OpsIndexRoute
  '/ops/bookings/$bookingId': typeof OpsBookingsBookingIdRoute
  '/ops/bookings/': typeof OpsBookingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ops'
    | '/book/$hotelCode'
    | '/confirmed/$token'
    | '/ops/drivers'
    | '/ops/hotels'
    | '/ops/login'
    | '/ops/vehicles'
    | '/ops/'
    | '/ops/bookings/$bookingId'
    | '/ops/bookings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book/$hotelCode'
    | '/confirmed/$token'
    | '/ops/drivers'
    | '/ops/hotels'
    | '/ops/login'
    | '/ops/vehicles'
    | '/ops'
    | '/ops/bookings/$bookingId'
    | '/ops/bookings'
  id:
    | '__root__'
    | '/'
    | '/ops'
    | '/book/$hotelCode'
    | '/confirmed/$token'
    | '/ops/drivers'
    | '/ops/hotels'
    | '/ops/login'
    | '/ops/vehicles'
    | '/ops/'
    | '/ops/bookings/$bookingId'
    | '/ops/bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpsRoute: typeof OpsRouteWithChildren
  BookHotelCodeRoute: typeof BookHotelCodeRoute
  ConfirmedTokenRoute: typeof ConfirmedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$hotelCode': {
      id: '/book/$hotelCode'
      path: '/book/$hotelCode'
      fullPath: '/book/$hotelCode'
      preLoaderRoute: typeof BookHotelCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmed/$token': {
      id: '/confirmed/$token'
      path: '/confirmed/$token'
      fullPath: '/confirmed/$token'
      preLoaderRoute: typeof ConfirmedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/drivers': {
      id: '/ops/drivers'
      path: '/drivers'
      fullPath: '/ops/drivers'
      preLoaderRoute: typeof OpsDriversRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/hotels': {
      id: '/ops/hotels'
      path: '/hotels'
      fullPath: '/ops/hotels'
      preLoaderRoute: typeof OpsHotelsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/login': {
      id: '/ops/login'
      path: '/login'
      fullPath: '/ops/login'
      preLoaderRoute: typeof OpsLoginRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/vehicles': {
      id: '/ops/vehicles'
      path: '/vehicles'
      fullPath: '/ops/vehicles'
      preLoaderRoute: typeof OpsVehiclesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/bookings/': {
      id: '/ops/bookings/'
      path: '/bookings'
      fullPath: '/ops/bookings/'
      preLoaderRoute: typeof OpsBookingsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/bookings/$bookingId': {
      id: '/ops/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/ops/bookings/$bookingId'
      preLoaderRoute: typeof OpsBookingsBookingIdRouteImport
      parentRoute: typeof OpsRoute
    }
  }
}

interface OpsRouteChildren {
  OpsDriversRoute: typeof OpsDriversRoute
  OpsHotelsRoute: typeof OpsHotelsRoute
  OpsLoginRoute: typeof OpsLoginRoute
  OpsVehiclesRoute: typeof OpsVehiclesRoute
  OpsIndexRoute: typeof OpsIndexRoute
  OpsBookingsBookingIdRoute: typeof OpsBookingsBookingIdRoute
  OpsBookingsIndexRoute: typeof OpsBookingsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsDriversRoute: OpsDriversRoute,
  OpsHotelsRoute: OpsHotelsRoute,
  OpsLoginRoute: OpsLoginRoute,
  OpsVehiclesRoute: OpsVehiclesRoute,
  OpsIndexRoute: OpsIndexRoute,
  OpsBookingsBookingIdRoute: OpsBookingsBookingIdRoute,
  OpsBookingsIndexRoute: OpsBookingsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpsRoute: OpsRouteWithChildren,
  BookHotelCodeRoute: BookHotelCodeRoute,
  ConfirmedTokenRoute: ConfirmedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
