/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotelSlugRouteImport } from './routes/$hotelSlug'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as BookHotelCodeRouteImport } from './routes/book.$hotelCode'
import { Route as ConfirmedTokenRouteImport } from './routes/confirmed.$token'
import { Route as OpsIndexRouteImport } from './routes/ops.index'
import { Route as OpsDriversRouteImport } from './routes/ops.drivers'
import { Route as OpsHotelsRouteImport } from './routes/ops.hotels'
import { Route as OpsLoginRouteImport } from './routes/ops.login'
import { Route as OpsVehiclesRouteImport } from './routes/ops.vehicles'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as OwnerLoginRouteImport } from './routes/owner.login'
import { Route as OwnerPlansRouteImport } from './routes/owner.plans'
import { Route as OwnerRevenueRouteImport } from './routes/owner.revenue'
import { Route as OwnerSystemRouteImport } from './routes/owner.system'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as AppHotelsHotelIdRouteImport } from './routes/app.hotels.$hotelId'
import { Route as OpsBookingsIndexRouteImport } from './routes/ops.bookings.index'
import { Route as OpsBookingsBookingIdRouteImport } from './routes/ops.bookings.$bookingId'
import { Route as OpsInternalRuntimeIdentityRouteImport } from './routes/ops.internal.runtime-identity'
import { Route as OwnerHotelsIndexRouteImport } from './routes/owner.hotels.index'
import { Route as OwnerHotelsHotelIdRouteImport } from './routes/owner.hotels.$hotelId'
import { Route as ApiStripeConnectCallbackRouteImport } from './routes/api/stripe/connect/callback'
import { Route as AppHotelsHotelIdPreviewRouteImport } from './routes/app.hotels.$hotelId.preview'
import { Route as AppHotelsHotelIdQrRouteImport } from './routes/app.hotels.$hotelId.qr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelSlugRoute = HotelSlugRouteImport.update({
  id: '/$hotelSlug',
  path: '/$hotelSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const BookHotelCodeRoute = BookHotelCodeRouteImport.update({
  id: '/book/$hotelCode',
  path: '/book/$hotelCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmedTokenRoute = ConfirmedTokenRouteImport.update({
  id: '/confirmed/$token',
  path: '/confirmed/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsDriversRoute = OpsDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => OpsRoute,
} as any)
const OpsHotelsRoute = OpsHotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => OpsRoute,
} as any)
const OpsLoginRoute = OpsLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => OpsRoute,
} as any)
const OpsVehiclesRoute = OpsVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => OpsRoute,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerLoginRoute = OwnerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPlansRoute = OwnerPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerRevenueRoute = OwnerRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSystemRoute = OwnerSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => OwnerRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHotelsHotelIdRoute = AppHotelsHotelIdRouteImport.update({
  id: '/hotels/$hotelId',
  path: '/hotels/$hotelId',
  getParentRoute: () => AppRoute,
} as any)
const OpsBookingsIndexRoute = OpsBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsBookingsBookingIdRoute = OpsBookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => OpsRoute,
} as any)
const OpsInternalRuntimeIdentityRoute =
  OpsInternalRuntimeIdentityRouteImport.update({
    id: '/internal/runtime-identity',
    path: '/internal/runtime-identity',
    getParentRoute: () => OpsRoute,
  } as any)
const OwnerHotelsIndexRoute = OwnerHotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerHotelsHotelIdRoute = OwnerHotelsHotelIdRouteImport.update({
  id: '/hotels/$hotelId',
  path: '/hotels/$hotelId',
  getParentRoute: () => OwnerRoute,
} as any)
const ApiStripeConnectCallbackRoute =
  ApiStripeConnectCallbackRouteImport.update({
    id: '/api/stripe/connect/callback',
    path: '/api/stripe/connect/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppHotelsHotelIdPreviewRoute = AppHotelsHotelIdPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AppHotelsHotelIdRoute,
} as any)
const AppHotelsHotelIdQrRoute = AppHotelsHotelIdQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AppHotelsHotelIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$hotelSlug': typeof HotelSlugRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/owner': typeof OwnerRouteWithChildren
  '/app/billing': typeof AppBillingRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/book/$hotelCode': typeof BookHotelCodeRoute
  '/confirmed/$token': typeof ConfirmedTokenRoute
  '/ops/drivers': typeof OpsDriversRoute
  '/ops/hotels': typeof OpsHotelsRoute
  '/ops/login': typeof OpsLoginRoute
  '/ops/vehicles': typeof OpsVehiclesRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/plans': typeof OwnerPlansRoute
  '/owner/revenue': typeof OwnerRevenueRoute
  '/owner/system': typeof OwnerSystemRoute
  '/app/': typeof AppIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/app/hotels/$hotelId': typeof AppHotelsHotelIdRouteWithChildren
  '/ops/bookings/$bookingId': typeof OpsBookingsBookingIdRoute
  '/ops/internal/runtime-identity': typeof OpsInternalRuntimeIdentityRoute
  '/owner/hotels/$hotelId': typeof OwnerHotelsHotelIdRoute
  '/ops/bookings/': typeof OpsBookingsIndexRoute
  '/owner/hotels/': typeof OwnerHotelsIndexRoute
  '/api/stripe/connect/callback': typeof ApiStripeConnectCallbackRoute
  '/app/hotels/$hotelId/preview': typeof AppHotelsHotelIdPreviewRoute
  '/app/hotels/$hotelId/qr': typeof AppHotelsHotelIdQrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$hotelSlug': typeof HotelSlugRoute
  '/login': typeof LoginRoute
  '/app/billing': typeof AppBillingRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/book/$hotelCode': typeof BookHotelCodeRoute
  '/confirmed/$token': typeof ConfirmedTokenRoute
  '/ops/drivers': typeof OpsDriversRoute
  '/ops/hotels': typeof OpsHotelsRoute
  '/ops/login': typeof OpsLoginRoute
  '/ops/vehicles': typeof OpsVehiclesRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/plans': typeof OwnerPlansRoute
  '/owner/revenue': typeof OwnerRevenueRoute
  '/owner/system': typeof OwnerSystemRoute
  '/app': typeof AppIndexRoute
  '/ops': typeof OpsIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/app/hotels/$hotelId': typeof AppHotelsHotelIdRouteWithChildren
  '/ops/bookings/$bookingId': typeof OpsBookingsBookingIdRoute
  '/ops/internal/runtime-identity': typeof OpsInternalRuntimeIdentityRoute
  '/owner/hotels/$hotelId': typeof OwnerHotelsHotelIdRoute
  '/ops/bookings': typeof OpsBookingsIndexRoute
  '/owner/hotels': typeof OwnerHotelsIndexRoute
  '/api/stripe/connect/callback': typeof ApiStripeConnectCallbackRoute
  '/app/hotels/$hotelId/preview': typeof AppHotelsHotelIdPreviewRoute
  '/app/hotels/$hotelId/qr': typeof AppHotelsHotelIdQrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$hotelSlug': typeof HotelSlugRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/owner': typeof OwnerRouteWithChildren
  '/app/billing': typeof AppBillingRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/book/$hotelCode': typeof BookHotelCodeRoute
  '/confirmed/$token': typeof ConfirmedTokenRoute
  '/ops/drivers': typeof OpsDriversRoute
  '/ops/hotels': typeof OpsHotelsRoute
  '/ops/login': typeof OpsLoginRoute
  '/ops/vehicles': typeof OpsVehiclesRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/plans': typeof OwnerPlansRoute
  '/owner/revenue': typeof OwnerRevenueRoute
  '/owner/system': typeof OwnerSystemRoute
  '/app/': typeof AppIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/app/hotels/$hotelId': typeof AppHotelsHotelIdRouteWithChildren
  '/ops/bookings/$bookingId': typeof OpsBookingsBookingIdRoute
  '/ops/internal/runtime-identity': typeof OpsInternalRuntimeIdentityRoute
  '/owner/hotels/$hotelId': typeof OwnerHotelsHotelIdRoute
  '/ops/bookings/': typeof OpsBookingsIndexRoute
  '/owner/hotels/': typeof OwnerHotelsIndexRoute
  '/api/stripe/connect/callback': typeof ApiStripeConnectCallbackRoute
  '/app/hotels/$hotelId/preview': typeof AppHotelsHotelIdPreviewRoute
  '/app/hotels/$hotelId/qr': typeof AppHotelsHotelIdQrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$hotelSlug'
    | '/app'
    | '/login'
    | '/ops'
    | '/owner'
    | '/app/billing'
    | '/app/onboarding'
    | '/book/$hotelCode'
    | '/confirmed/$token'
    | '/ops/drivers'
    | '/ops/hotels'
    | '/ops/login'
    | '/ops/vehicles'
    | '/owner/login'
    | '/owner/plans'
    | '/owner/revenue'
    | '/owner/system'
    | '/app/'
    | '/ops/'
    | '/owner/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/app/hotels/$hotelId'
    | '/ops/bookings/$bookingId'
    | '/ops/internal/runtime-identity'
    | '/owner/hotels/$hotelId'
    | '/ops/bookings/'
    | '/owner/hotels/'
    | '/api/stripe/connect/callback'
    | '/app/hotels/$hotelId/preview'
    | '/app/hotels/$hotelId/qr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$hotelSlug'
    | '/login'
    | '/app/billing'
    | '/app/onboarding'
    | '/book/$hotelCode'
    | '/confirmed/$token'
    | '/ops/drivers'
    | '/ops/hotels'
    | '/ops/login'
    | '/ops/vehicles'
    | '/owner/login'
    | '/owner/plans'
    | '/owner/revenue'
    | '/owner/system'
    | '/app'
    | '/ops'
    | '/owner'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/app/hotels/$hotelId'
    | '/ops/bookings/$bookingId'
    | '/ops/internal/runtime-identity'
    | '/owner/hotels/$hotelId'
    | '/ops/bookings'
    | '/owner/hotels'
    | '/api/stripe/connect/callback'
    | '/app/hotels/$hotelId/preview'
    | '/app/hotels/$hotelId/qr'
  id:
    | '__root__'
    | '/'
    | '/$hotelSlug'
    | '/app'
    | '/login'
    | '/ops'
    | '/owner'
    | '/app/billing'
    | '/app/onboarding'
    | '/book/$hotelCode'
    | '/confirmed/$token'
    | '/ops/drivers'
    | '/ops/hotels'
    | '/ops/login'
    | '/ops/vehicles'
    | '/owner/login'
    | '/owner/plans'
    | '/owner/revenue'
    | '/owner/system'
    | '/app/'
    | '/ops/'
    | '/owner/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/app/hotels/$hotelId'
    | '/ops/bookings/$bookingId'
    | '/ops/internal/runtime-identity'
    | '/owner/hotels/$hotelId'
    | '/ops/bookings/'
    | '/owner/hotels/'
    | '/api/stripe/connect/callback'
    | '/app/hotels/$hotelId/preview'
    | '/app/hotels/$hotelId/qr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HotelSlugRoute: typeof HotelSlugRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRouteWithChildren
  OwnerRoute: typeof OwnerRouteWithChildren
  BookHotelCodeRoute: typeof BookHotelCodeRoute
  ConfirmedTokenRoute: typeof ConfirmedTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiStripeConnectCallbackRoute: typeof ApiStripeConnectCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$hotelSlug': {
      id: '/$hotelSlug'
      path: '/$hotelSlug'
      fullPath: '/$hotelSlug'
      preLoaderRoute: typeof HotelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/book/$hotelCode': {
      id: '/book/$hotelCode'
      path: '/book/$hotelCode'
      fullPath: '/book/$hotelCode'
      preLoaderRoute: typeof BookHotelCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmed/$token': {
      id: '/confirmed/$token'
      path: '/confirmed/$token'
      fullPath: '/confirmed/$token'
      preLoaderRoute: typeof ConfirmedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/drivers': {
      id: '/ops/drivers'
      path: '/drivers'
      fullPath: '/ops/drivers'
      preLoaderRoute: typeof OpsDriversRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/hotels': {
      id: '/ops/hotels'
      path: '/hotels'
      fullPath: '/ops/hotels'
      preLoaderRoute: typeof OpsHotelsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/login': {
      id: '/ops/login'
      path: '/login'
      fullPath: '/ops/login'
      preLoaderRoute: typeof OpsLoginRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/vehicles': {
      id: '/ops/vehicles'
      path: '/vehicles'
      fullPath: '/ops/vehicles'
      preLoaderRoute: typeof OpsVehiclesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/login': {
      id: '/owner/login'
      path: '/login'
      fullPath: '/owner/login'
      preLoaderRoute: typeof OwnerLoginRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/plans': {
      id: '/owner/plans'
      path: '/plans'
      fullPath: '/owner/plans'
      preLoaderRoute: typeof OwnerPlansRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/revenue': {
      id: '/owner/revenue'
      path: '/revenue'
      fullPath: '/owner/revenue'
      preLoaderRoute: typeof OwnerRevenueRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/system': {
      id: '/owner/system'
      path: '/system'
      fullPath: '/owner/system'
      preLoaderRoute: typeof OwnerSystemRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/hotels/$hotelId': {
      id: '/app/hotels/$hotelId'
      path: '/hotels/$hotelId'
      fullPath: '/app/hotels/$hotelId'
      preLoaderRoute: typeof AppHotelsHotelIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/ops/bookings/': {
      id: '/ops/bookings/'
      path: '/bookings'
      fullPath: '/ops/bookings/'
      preLoaderRoute: typeof OpsBookingsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/bookings/$bookingId': {
      id: '/ops/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/ops/bookings/$bookingId'
      preLoaderRoute: typeof OpsBookingsBookingIdRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/internal/runtime-identity': {
      id: '/ops/internal/runtime-identity'
      path: '/internal/runtime-identity'
      fullPath: '/ops/internal/runtime-identity'
      preLoaderRoute: typeof OpsInternalRuntimeIdentityRouteImport
      parentRoute: typeof OpsRoute
    }
    '/owner/hotels/': {
      id: '/owner/hotels/'
      path: '/hotels'
      fullPath: '/owner/hotels/'
      preLoaderRoute: typeof OwnerHotelsIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/hotels/$hotelId': {
      id: '/owner/hotels/$hotelId'
      path: '/hotels/$hotelId'
      fullPath: '/owner/hotels/$hotelId'
      preLoaderRoute: typeof OwnerHotelsHotelIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/api/stripe/connect/callback': {
      id: '/api/stripe/connect/callback'
      path: '/api/stripe/connect/callback'
      fullPath: '/api/stripe/connect/callback'
      preLoaderRoute: typeof ApiStripeConnectCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/hotels/$hotelId/preview': {
      id: '/app/hotels/$hotelId/preview'
      path: '/preview'
      fullPath: '/app/hotels/$hotelId/preview'
      preLoaderRoute: typeof AppHotelsHotelIdPreviewRouteImport
      parentRoute: typeof AppHotelsHotelIdRoute
    }
    '/app/hotels/$hotelId/qr': {
      id: '/app/hotels/$hotelId/qr'
      path: '/qr'
      fullPath: '/app/hotels/$hotelId/qr'
      preLoaderRoute: typeof AppHotelsHotelIdQrRouteImport
      parentRoute: typeof AppHotelsHotelIdRoute
    }
  }
}

interface AppHotelsHotelIdRouteChildren {
  AppHotelsHotelIdPreviewRoute: typeof AppHotelsHotelIdPreviewRoute
  AppHotelsHotelIdQrRoute: typeof AppHotelsHotelIdQrRoute
}

const AppHotelsHotelIdRouteChildren: AppHotelsHotelIdRouteChildren = {
  AppHotelsHotelIdPreviewRoute: AppHotelsHotelIdPreviewRoute,
  AppHotelsHotelIdQrRoute: AppHotelsHotelIdQrRoute,
}

const AppHotelsHotelIdRouteWithChildren =
  AppHotelsHotelIdRoute._addFileChildren(AppHotelsHotelIdRouteChildren)

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppHotelsHotelIdRoute: typeof AppHotelsHotelIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppIndexRoute: AppIndexRoute,
  AppHotelsHotelIdRoute: AppHotelsHotelIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OpsRouteChildren {
  OpsDriversRoute: typeof OpsDriversRoute
  OpsHotelsRoute: typeof OpsHotelsRoute
  OpsLoginRoute: typeof OpsLoginRoute
  OpsVehiclesRoute: typeof OpsVehiclesRoute
  OpsIndexRoute: typeof OpsIndexRoute
  OpsBookingsBookingIdRoute: typeof OpsBookingsBookingIdRoute
  OpsInternalRuntimeIdentityRoute: typeof OpsInternalRuntimeIdentityRoute
  OpsBookingsIndexRoute: typeof OpsBookingsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsDriversRoute: OpsDriversRoute,
  OpsHotelsRoute: OpsHotelsRoute,
  OpsLoginRoute: OpsLoginRoute,
  OpsVehiclesRoute: OpsVehiclesRoute,
  OpsIndexRoute: OpsIndexRoute,
  OpsBookingsBookingIdRoute: OpsBookingsBookingIdRoute,
  OpsInternalRuntimeIdentityRoute: OpsInternalRuntimeIdentityRoute,
  OpsBookingsIndexRoute: OpsBookingsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

interface OwnerRouteChildren {
  OwnerLoginRoute: typeof OwnerLoginRoute
  OwnerPlansRoute: typeof OwnerPlansRoute
  OwnerRevenueRoute: typeof OwnerRevenueRoute
  OwnerSystemRoute: typeof OwnerSystemRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  OwnerHotelsHotelIdRoute: typeof OwnerHotelsHotelIdRoute
  OwnerHotelsIndexRoute: typeof OwnerHotelsIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerLoginRoute: OwnerLoginRoute,
  OwnerPlansRoute: OwnerPlansRoute,
  OwnerRevenueRoute: OwnerRevenueRoute,
  OwnerSystemRoute: OwnerSystemRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  OwnerHotelsHotelIdRoute: OwnerHotelsHotelIdRoute,
  OwnerHotelsIndexRoute: OwnerHotelsIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HotelSlugRoute: HotelSlugRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRouteWithChildren,
  OwnerRoute: OwnerRouteWithChildren,
  BookHotelCodeRoute: BookHotelCodeRoute,
  ConfirmedTokenRoute: ConfirmedTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiStripeConnectCallbackRoute: ApiStripeConnectCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
